---
title: "Employee Attrition and Engagement Exploration"
output: html_document
date: "2024-02-14"
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load dataset


```{r cars}
data <- read.csv("C:/Users/golde/Data-Visualization/hw2/employee_attrition_and_engagement.csv")

```

## Summaries

```{r}
hist(data$Age)

data$Logical_Attrition <- ifelse(data$Attrition == "Yes", 1, 0)
table(data$Logical_Attrition)

boxplot(JobSatisfaction ~ Attrition, data = data)
boxplot(DistanceFromHome ~ Attrition, data = data)

plot(data$DistanceFromHome, data$JobSatisfaction)

table(data$StandardHours)
table(data$PerformanceRating)
```

## Distance from home and satisfaction
```{r}
library(tidyverse)
data$Attrition <- as.factor(data$Attrition)

ggplot(data, aes(x = DistanceFromHome, y = JobSatisfaction, color = factor(Attrition))) + geom_jitter() 

cor(data$DistanceFromHome, data$Logical_Attrition)

cor(data$EnvironmentSatisfaction, data$JobSatisfaction)
```

## Salary and satisfaction
```{r}
ggplot(data, aes(x = MonthlyIncome, y = JobSatisfaction, color = factor(Attrition))) + geom_jitter() 

cor(data$MonthlyIncome, data$JobSatisfaction)
cor(data$HourlyRate, data$JobSatisfaction)
cor(data$WorkLifeBalance, data$JobSatisfaction)
```

## Correlations by Department
```{r}
boxplot(HourlyRate ~ Department, data = data)
boxplot(EnvironmentSatisfaction ~ Department, data = data)
boxplot(JobSatisfaction ~ Department, data = data)
boxplot(MonthlyIncome ~ Department, data = data)
boxplot(WorkLifeBalance ~ Department, data = data)
```

## Satisfaction
```{r}
hr <- data[data$Department == "Human Resources",]
rd <- data[data$Department == "Research & Development",]
sales <- data[data$Department == "Sales",]

hr_sat <- table(hr$JobSatisfaction)
hr_prop <- prop.table(hr_sat)

rd_sat <- table(rd$JobSatisfaction)
rd_prop <-prop.table(rd_sat)

sales_sat <- table(sales$JobSatisfaction)
sales_prop <-prop.table(sales_sat)

par(mfrow=c(1,3))
barplot(hr_prop, col = "azure", main="Human Resources")
barplot(rd_prop, col = "plum", main="Research & Development")
barplot(sales_prop, col = "lightgreen", main="Sales")
```

## Worklifebalance
```{r}
hr_wlb <- table(hr$WorkLifeBalance)
hr_prop <- prop.table(hr_wlb)

rd_wlb <- table(rd$WorkLifeBalance)
rd_prop <-prop.table(rd_wlb)

sales_wlb <- table(sales$WorkLifeBalance)
sales_prop <-prop.table(sales_wlb)

par(mfrow=c(1,3))
barplot(hr_prop, col = "azure", main="Human Resources")
barplot(rd_prop, col = "plum", main="Research & Development")
barplot(sales_prop, col = "lightgreen", main="Sales")
```

## JobInvolvement
```{r}
hr_ji <- table(hr$JobInvolvement)
hr_prop <- prop.table(hr_ji)

rd_ji  <- table(rd$JobInvolvement)
rd_prop <-prop.table(rd_ji)

sales_ji  <- table(sales$JobInvolvement)
sales_prop <-prop.table(sales_ji)

par(mfrow=c(1,3))
barplot(hr_prop, col = "azure", main="Human Resources")
barplot(rd_prop, col = "plum", main="Research & Development")
barplot(sales_prop, col = "lightgreen", main="Sales")
```

## PerformanceRating
```{r}
hr_pr <- table(hr$PerformanceRating)
hr_prop <- prop.table(hr_pr)

rd_pr  <- table(rd$PerformanceRating)
rd_prop <-prop.table(rd_pr)

sales_pr  <- table(sales$PerformanceRating)
sales_prop <-prop.table(sales_pr)

par(mfrow=c(1,3))
barplot(hr_prop, col = "azure", main="Human Resources")
barplot(rd_prop, col = "plum", main="Research & Development")
barplot(sales_prop, col = "lightgreen", main="Sales")
```

## RelationshipSatisfaction
```{r}
hr_rel <- table(hr$RelationshipSatisfaction)
hr_prop <- prop.table(hr_rel)

rd_rel  <- table(rd$RelationshipSatisfaction)
rd_prop <-prop.table(rd_rel)

sales_rel  <- table(sales$RelationshipSatisfaction)
sales_prop <-prop.table(sales_rel)

par(mfrow=c(1,3))
barplot(hr_prop, col = "azure", main="Human Resources")
barplot(rd_prop, col = "plum", main="Research & Development")
barplot(sales_prop, col = "lightgreen", main="Sales")
```


## Monthly Income
```{r}

par(mfrow=c(1,3))
hist(hr$MonthlyIncome, breaks = 25, col = "azure", main="Human Resources")
hist(rd$MonthlyIncome, breaks = 25, col = "plum", main="Research & Development")
hist(sales$MonthlyIncome, breaks = 25, col = "lightgreen", main="Sales")
```


